Add more info about filters to docs and rename struct fields
prometheus-community/stackdriver_exporter pull request #198
Opened 2023-01-31 20:49 UTC by kgeckhart

Adds some more details docs regarding `monitoring.filters`. Similar to #165, I found it hard to use the filters initially so hopefully more detailed docs can help. Especially related to the fact that the `monitoring.filters` flag should be specified multiple times vs comma delimited like other multi-valued params.

2023-03-16 13:38 UTC, kgeckhart commented
> This looks good, is there someone who can review it?

I think only @SuperQ can approve PR's ATM

2023-11-20 10:03 UTC, BenCoughlan15 commented
Hey @SuperQ  - I'm bumping into this again, It would really save me a tonne of bother if we could get this approved. 🙏

2024-03-07 16:01 UTC, SuperQ requested changes
This needs a rebase.

2024-03-18 20:55 UTC, kgeckhart commented
Should be good to go now @SuperQ

2024-06-04 06:52 UTC, SuperQ approved these changes
Thanks!

2024-06-04 06:52 UTC, merged