Add support for aggregations.
prometheus-community/stackdriver_exporter pull request #34
Opened 2018-07-24 09:40 UTC by tcolgate

This adds support for setting an aggregation. This aggregation is used
for all metrics collection by the exporter. It adjust the resulting
metric names into prometheus recording rule style to allow for
different exporters to collect different aggregations.

We add support for passing the fields, reducer, aligner and align
duration as per other options.

resulting metrics look as follows

'''target_proxy_name_response_code:stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_backend_latencies:sum_bucket{...}```

2018-07-24 09:42 UTC, tcolgate commented
This is just work in progress to see if you would be interested in this, and if so, to discuss the overall design. Issues with this implementaiton:

- The aggregation is applied to the entire exporter, not per metrics prefix (it would make more sense, but the resulting UI could be a big gnarly)
- The metrics names aren't quite right, this could be fixed by manuall producing the const histsogram metrics.
- Not fixed up the tests as yet.

2020-05-01 11:21 UTC, SuperQ commented
This is an interesting idea. It looks like the change needs to be rebaesd.

One comment, exporters should not use `:` in metric names, since this is reserved for recording rules.

2020-06-12 13:34 UTC, tcolgate commented
@SuperQ so, my thinking here was that the metric is already aggregated so that the names attempt to match what you'd get if you created a recording rule for the same purpose. Other than replacing with an underscore, do you have any other ideas regarding naming?

2020-06-12 13:36 UTC, tcolgate commented
FWIW, we never used this code, because I didn't really ant to maintain yet another fork in house, but I'd be happy to polish this PR , since it does seem like useful functionality. May not have time in the next two weeks though.

2020-06-28 09:59 UTC, SuperQ commented
I think we can just close this. I think aggregating in the exporter might be a bit more than we want to support.

2020-06-29 12:14 UTC, SuperQ commented
After having a discussion on Slack, and looking at some of the use of Stackdriver data we have, this is more useful than I previously thought.

2020-08-27 12:51 UTC, SuperQ commented
Any interest in reviving this?

2020-08-27 13:47 UTC, SuperQ commented
I experimented with this a bit, I think there needs to be some changes.

In order for this to be useful generally, we need to supply per-metrics-prefix aggregation requests. Otherwise it will try and apply aggregations to prefixes that don't make sense.

I'm thinking something along the lines of this:
```
networking.googleapis.com/vm_flow/egress_bytes_count|fields=metric.label.remote_subnetwork;aligner=ALIGN_DELTA;reducer=REDUCE_SUM;period=1m
```

Part of the problem here, is we still accept ENV vars for input. This makes command line parsing much more difficult, as we need a lot of string separators.

IMO, I think we need to drop the ENV vars, and change the `--monitoring.metrics-type-prefixes` to a single input, multi-flag.

2020-09-02 07:11 UTC, tcolgate commented
Sorry for the late response, I'll need to take some time to get my head around this again.

2020-09-02 09:41 UTC, SuperQ commented
@tcolgate No worries. I had some more thoughts about this, and I think the best way forward would be to move the metrics prefixes to a config file. I've filed https://github.com/prometheus-community/stackdriver_exporter/issues/106 to track this idea.

Basically, it would be more like the balckbox/snmp exporters. Rather than just a list of "metrics prefixes", there would be scrape modules with different prefixes and aggregations.

2020-12-04 10:34 UTC, priximmo commented
Hi, @tcolgate have you find another solution to collect stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_backend_latencies. I search to scrape the same metric with prometheus. Cardinalities of this metric don't help us.

Maybe have you found another solution ?

Thank you for your help.

2023-04-21 05:00 UTC, yyzh1 commented
sorry for digging up an old thread. is this still being worked on?

2024-03-07 16:02 UTC, SuperQ requested changes
This needs a rebase.

2025-02-10 16:22 UTC, Daniel-Vaz commented
I was trying to make some progress on this subject and started some testing work here - https://github.com/prometheus-community/stackdriver_exporter/compare/master...Daniel-Vaz:stackdriver_exporter:master

I now discovered this thread and especially [this suggestion](https://github.com/prometheus-community/stackdriver_exporter/pull/34#issuecomment-681959697) by @SuperQ  .

Is it worth to keep pursuing the approach of providing the extra Aggregation parameters through the existing `monitoring.metrics-prefixes` flag ?

For me, this seems more easy to implement than introducing the config-file based approach.

2025-02-18 12:33 UTC, tcolgate commented
@Daniel-Vaz Could you open your own PR once you've rebased? I can't work on this, so will close this.

2025-02-18 12:33 UTC, closed without merging

2025-05-15 07:01 UTC, ayan-kf commented
@tcolgate @Daniel-Vaz Is this something that you're continuing work on? 

I am running into a similar use of requiring per metric level aggregation and this seems like it will be helpful. Any update regarding the same would be helpful. Thanks!

2025-05-15 07:14 UTC, tcolgate commented
I'm not working on it at the moment as I'm not currently using the exporter.